// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rosa/runner.go
//
// Generated by this command:
//
//	mockgen-v0.4.0 --build_flags=--mod=mod -package mocks -destination=pkg/rosa/mocks/mock_cmd.go -source=pkg/rosa/runner.go CommandInterface
//

// Package mocks is a generated GoMock package.
package mocks
