coverage:
  status:
    project:
      default:
        paths:
          - "cmd"
          - "pkg"
    patch:
      default:
        paths:
          - "cmd"
          - "pkg"
        informational: true
ignore:
  - "pkg/aws/mock_client.go"