// Code generated by MockGen. DO NOT EDIT.
// Source: cmd.go
//
// Generated by this command:
//
//	mockgen -source=cmd.go -package=rosa -destination=./cmd_mock.go
//

// Package rosa is a generated GoMock package.
package rosa

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyRosa is a mock of VerifyRosa interface.
type MockVerifyRosa struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyRosaMockRecorder
}

// MockVerifyRosaMockRecorder is the mock recorder for MockVerifyRosa.
type MockVerifyRosaMockRecorder struct {
	mock *MockVerifyRosa
}

// NewMockVerifyRosa creates a new mock instance.
func NewMockVerifyRosa(ctrl *gomock.Controller) *MockVerifyRosa {
	mock := &MockVerifyRosa{ctrl: ctrl}
	mock.recorder = &MockVerifyRosaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyRosa) EXPECT() *MockVerifyRosaMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockVerifyRosa) Verify() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify")
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockVerifyRosaMockRecorder) Verify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockVerifyRosa)(nil).Verify))
}
