// Code generated by pathbind-gen. DO NOT EDIT.

package pathbind

import "github.com/spf13/pflag"

// registerIfNew calls register only when no flag named name is already defined on f.
// This makes Register*Flags safe to call after OCM v1 flag registrations for any flag type.
func registerIfNew(f *pflag.FlagSet, name string, register func()) {
	if f.Lookup(name) == nil {
		register()
	}
}
