// Code generated by pathbind-gen --mode=cobra. DO NOT EDIT.
// Source: pathbind-overrides.yaml
// Generated: 2026-09-03T15:25:30Z

package pathbind

import (
	"context"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	pathbind "github.com/openshift-online/rosa-hyperfleet-api/clientset/pathbind"
	platform "github.com/openshift-online/rosa-hyperfleet-api/clientset/platform"
	interactive "github.com/openshift/rosa/pkg/interactive"
	rosa "github.com/openshift/rosa/pkg/rosa"
	"github.com/spf13/cobra"
)

// NodePoolCreateInput holds directly-mappable inputs for NodePool create.
// All non-service-set SDK fields appear here; derived fields (no flag) are set in PreRequest.
type NodePoolCreateInput struct {
	Name                          string `hfsdk:"metadata.name"`
	AutoRepair                    *bool  `hfsdk:"spec.autoRepair"`
	DisplayName                   string `hfsdk:"spec.displayName"`
	Labels                        string `hfsdk:"spec.labels"`
	ClusterName                   string `hfsdk:"spec.nodePool.clusterName"`
	Ami                           string `hfsdk:"spec.nodePool.platform.aws.ami"`
	ImageType                     string `hfsdk:"spec.nodePool.platform.aws.imageType"`
	InstanceProfile               string `hfsdk:"spec.nodePool.platform.aws.instanceProfile"`
	InstanceType                  string `hfsdk:"spec.nodePool.platform.aws.instanceType"`
	CapacityReservationId         string `hfsdk:"spec.nodePool.platform.aws.placement.capacityReservation.id"`
	CapacityReservationMarketType string `hfsdk:"spec.nodePool.platform.aws.placement.capacityReservation.marketType"`
	Preference                    string `hfsdk:"spec.nodePool.platform.aws.placement.capacityReservation.preference"`
	PlacementMarketType           string `hfsdk:"spec.nodePool.platform.aws.placement.marketType"`
	MaxPrice                      string `hfsdk:"spec.nodePool.platform.aws.placement.spot.maxPrice"`
	Tenancy                       string `hfsdk:"spec.nodePool.platform.aws.placement.tenancy"`
	ResourceTags                  string `hfsdk:"spec.nodePool.platform.aws.resourceTags"`
	Encrypted                     *bool  `hfsdk:"spec.nodePool.platform.aws.rootVolume.encrypted"`
	EncryptionKey                 string `hfsdk:"spec.nodePool.platform.aws.rootVolume.encryptionKey"`
	Iops                          *int64 `hfsdk:"spec.nodePool.platform.aws.rootVolume.iops"`
	Size                          *int64 `hfsdk:"spec.nodePool.platform.aws.rootVolume.size"`
	RootVolumeType                string `hfsdk:"spec.nodePool.platform.aws.rootVolume.type"`
	SecurityGroups                string `hfsdk:"spec.nodePool.platform.aws.securityGroups"`
	Filters                       string `hfsdk:"spec.nodePool.platform.aws.subnet.filters"`
	SubnetID                      string `hfsdk:"spec.nodePool.platform.aws.subnet.id"`
	PlatformType                  string `hfsdk:"spec.nodePool.platform.type"`
	Image                         string `hfsdk:"spec.nodePool.release.image"`
	Replicas                      *int32 `hfsdk:"spec.nodePool.replicas"`
}

// NodePoolCreatePlatformAPIFlags lists the cobra flag names registered by
// RegisterNodePoolCreateFlags. Consumers use this to mark them in a help section
// without hardcoding the list a second time.
var NodePoolCreatePlatformAPIFlags = []string{
	"name",
	"auto-repair",
	"display-name",
	"labels",
	"cluster-name",
	"ami",
	"image-type",
	"instance-profile",
	"instance-type",
	"capacity-reservation-id",
	"capacity-reservation-market-type",
	"preference",
	"placement-market-type",
	"max-price",
	"tenancy",
	"resource-tags",
	"encrypted",
	"encryption-key",
	"iops",
	"size",
	"root-volume-type",
	"security-groups",
	"filters",
	"subnet",
	"platform-type",
	"image",
	"replicas",
}

// RegisterNodePoolCreateFlags registers cobra flags for user-settable NodePool create inputs.
// Flags whose names are already registered (e.g. by OCM v1 initFlags) are silently skipped.
func RegisterNodePoolCreateFlags(cmd *cobra.Command, input *NodePoolCreateInput) {
	f := cmd.Flags()
	registerIfNew(f, "name", func() { f.StringVar(&input.Name, "name", "", "Name of the node pool.") })
	registerIfNew(f, "auto-repair", func() { input.AutoRepair = new(bool); f.BoolVar(input.AutoRepair, "auto-repair", false, "") })
	registerIfNew(f, "display-name", func() { f.StringVar(&input.DisplayName, "display-name", "", "") })
	registerIfNew(f, "labels", func() { f.StringVar(&input.Labels, "labels", "", "") })
	registerIfNew(f, "cluster-name", func() { f.StringVar(&input.ClusterName, "cluster-name", "", "") })
	registerIfNew(f, "ami", func() { f.StringVar(&input.Ami, "ami", "", "") })
	registerIfNew(f, "image-type", func() { f.StringVar(&input.ImageType, "image-type", "", "") })
	registerIfNew(f, "instance-profile", func() { f.StringVar(&input.InstanceProfile, "instance-profile", "", "") })
	registerIfNew(f, "instance-type", func() { f.StringVar(&input.InstanceType, "instance-type", "", "AWS instance type for worker nodes.") })
	registerIfNew(f, "capacity-reservation-id", func() { f.StringVar(&input.CapacityReservationId, "capacity-reservation-id", "", "") })
	registerIfNew(f, "capacity-reservation-market-type", func() { f.StringVar(&input.CapacityReservationMarketType, "capacity-reservation-market-type", "", "") })
	registerIfNew(f, "preference", func() { f.StringVar(&input.Preference, "preference", "", "") })
	registerIfNew(f, "placement-market-type", func() { f.StringVar(&input.PlacementMarketType, "placement-market-type", "", "") })
	registerIfNew(f, "max-price", func() { f.StringVar(&input.MaxPrice, "max-price", "", "") })
	registerIfNew(f, "tenancy", func() { f.StringVar(&input.Tenancy, "tenancy", "", "") })
	registerIfNew(f, "resource-tags", func() { f.StringVar(&input.ResourceTags, "resource-tags", "", "") })
	registerIfNew(f, "encrypted", func() { input.Encrypted = new(bool); f.BoolVar(input.Encrypted, "encrypted", false, "") })
	registerIfNew(f, "encryption-key", func() { f.StringVar(&input.EncryptionKey, "encryption-key", "", "") })
	registerIfNew(f, "iops", func() { input.Iops = new(int64); f.Int64Var(input.Iops, "iops", 0, "") })
	registerIfNew(f, "size", func() { input.Size = new(int64); f.Int64Var(input.Size, "size", 0, "") })
	registerIfNew(f, "root-volume-type", func() { f.StringVar(&input.RootVolumeType, "root-volume-type", "", "") })
	registerIfNew(f, "security-groups", func() { f.StringVar(&input.SecurityGroups, "security-groups", "", "") })
	registerIfNew(f, "filters", func() { f.StringVar(&input.Filters, "filters", "", "") })
	registerIfNew(f, "subnet", func() { f.StringVar(&input.SubnetID, "subnet", "", "Subnet ID for the node pool.") })
	registerIfNew(f, "platform-type", func() { f.StringVar(&input.PlatformType, "platform-type", "", "") })
	registerIfNew(f, "image", func() { f.StringVar(&input.Image, "image", "", "") })
	registerIfNew(f, "replicas", func() {
		input.Replicas = new(int32)
		f.Int32Var(input.Replicas, "replicas", 0, "Number of worker nodes.")
	})
}

// NodePoolCreateHandler is implemented by consumers to provide NodePool create logic.
type NodePoolCreateHandler interface {
	// Prompt fills missing inputs interactively (called only when interactive.Enabled()).
	// Embed GeneratedNodePoolCreatePrompt to inherit auto-generated prompting for required fields.
	Prompt(ctx context.Context, r *rosa.Runtime, cmd *cobra.Command, input *NodePoolCreateInput) error
	// PreRequest validates inputs and derives computed fields (e.g. subnet → VPC/zone).
	PreRequest(ctx context.Context, r *rosa.Runtime, input *NodePoolCreateInput) error
	// PostExpand sets SDK fields pathbind cannot express (constants, computed structs).
	PostExpand(ctx context.Context, r *rosa.Runtime, input *NodePoolCreateInput, obj *v1alpha1.NodePool) error
	// PostResponse handles the SDK response (output formatting, side effects).
	PostResponse(ctx context.Context, r *rosa.Runtime, obj *v1alpha1.NodePool) error
}

// GeneratedNodePoolCreatePrompt provides auto-generated interactive prompting for required create fields.
// Embed in your NodePoolCreateHandler to inherit it; override Prompt() to extend.
type GeneratedNodePoolCreatePrompt struct{}

func (GeneratedNodePoolCreatePrompt) Prompt(ctx context.Context, r *rosa.Runtime, cmd *cobra.Command, input *NodePoolCreateInput) error {
	var err error
	if input.Name == "" {
		input.Name, err = interactive.GetString(interactive.Input{Question: "Name of the node pool.", Help: cmd.Flags().Lookup("name").Usage, Required: true})
		if err != nil {
			return err
		}
	}
	if input.SubnetID == "" {
		input.SubnetID, err = interactive.GetString(interactive.Input{Question: "Subnet ID for the node pool.", Help: cmd.Flags().Lookup("subnet").Usage, Required: true})
		if err != nil {
			return err
		}
	}
	return nil
}

// normalizeNodePoolCreateInput clears numeric pointer fields that were pre-allocated by
// cobra but not actually set by the user. This allows pathbind.Expand to distinguish
// between "not set" (nil) and "explicitly set to zero".
func normalizeNodePoolCreateInput(cmd *cobra.Command, input *NodePoolCreateInput) {

	if cmd == nil {
		return
	}
	if cmd.Flags().Lookup("iops") != nil && !cmd.Flag("iops").Changed &&
		input.Iops != nil {
		input.Iops = nil
	}
	if cmd == nil {
		return
	}
	if cmd.Flags().Lookup("size") != nil && !cmd.Flag("size").Changed &&
		input.Size != nil {
		input.Size = nil
	}
	if cmd == nil {
		return
	}
	if cmd.Flags().Lookup("replicas") != nil && !cmd.Flag("replicas").Changed &&
		input.Replicas != nil {
		input.Replicas = nil
	}
}

// RunCreateNodePool executes the create dispatch. Generated; do not edit.
func RunCreateNodePool(ctx context.Context, r *rosa.Runtime, cmd *cobra.Command, input *NodePoolCreateInput, h NodePoolCreateHandler, namespace string) error {
	if interactive.Enabled() {
		if err := h.Prompt(ctx, r, cmd, input); err != nil {
			return err
		}
	}
	if err := h.PreRequest(ctx, r, input); err != nil {
		return err
	}
	normalizeNodePoolCreateInput(cmd, input)
	obj := &v1alpha1.NodePool{}
	if err := pathbind.Expand(ctx, *input, obj); err != nil {
		return err
	}
	if err := h.PostExpand(ctx, r, input, obj); err != nil {
		return err
	}
	created, err := r.HyperFleetClient.HyperfleetV1alpha1().NodePools(namespace).Create(ctx, obj, platform.CreateOptions{})
	if err != nil {
		return err
	}
	return h.PostResponse(ctx, r, created)
}
