apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: clean-up
spec:
  description: |
    This is a step to clean up all testing resources
  image: $(params.container-image)
  imagePullPolicy: Always
  workingDir: /rosa
  params:
    - name: container-image
    - name: secret-volume
    - name: output-volume
    - name: secret-ref
    - name: channel-group
    - name: aws-region
    - name: cluster-profile
  results:
    - name: passed
      description: It shows if the step is passed or failed
    - name: failedCases
      description: It shows the failed cases run the the test
  volumeMounts:
    - name: $(params.secret-volume)
      mountPath: /mnt/secrets
    - name: $(params.output-volume)
      mountPath: /tests/output
  env:
    - name: AWS_CREDENTIALS
      value: "/mnt/secrets/aws_cred"
    - name: AWS_SHAREDVPC_CREDENTIALS
      value: "/mnt/secrets/aws_cred"
    - name: OCM_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.secret-ref)
          key: oex_org_admin_token
    - name: OCM_LOGIN_ENV
      value: $(params.channel-group)
    - name: AWS_REGION
      value: $(params.aws-region)
    - name: TEST_PROFILE
      value: $(params.cluster-profile)
  
  script: |
    #!/bin/bash
    # setup rosacli
    source ./tests/prow_ci.sh
    configure_aws "${AWS_CREDENTIALS}" "${AWS_REGION}"
    configure_aws_shared_vpc "${AWS_SHAREDVPC_CREDENTIALS}/.awscred_shared_account"

    rosa login --env ${OCM_LOGIN_ENV} --token ${OCM_TOKEN}
    rosa whoami

    # run destroy case to clean up all testing resources
    go install github.com/onsi/ginkgo/v2/ginkgo@latest
    ginkgo ./tests/e2e --ginkgo.v --ginkgo.no-color \
      --ginkgo.timeout "1h" \
      --ginkgo.label-filter "destroy"
    rc1=$?

     # run destroy-post case to check if all resources are cleaned up
    ginkgo ./tests/e2e --ginkgo.v --ginkgo.no-color \
      --ginkgo.timeout "30m" \
      --ginkgo.label-filter "destroy-post"
    rc2=$?
    if [ $rc1 -ne 0 ] || [ $rc2 -ne 0 ]; then
      exit 1
    fi

    


