// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/openshift-online/rosa-hyperfleet-api/clientset/hyperfleet.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -source=vendor/github.com/openshift-online/rosa-hyperfleet-api/clientset/hyperfleet.go -package=mocks -destination=pkg/hyperfleet/mocks/hyperfleet_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	platform "github.com/openshift-online/rosa-hyperfleet-api/clientset/platform"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// HyperfleetV1alpha1 mocks base method.
func (m *MockInterface) HyperfleetV1alpha1() platform.V1alpha1PublicInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HyperfleetV1alpha1")
	ret0, _ := ret[0].(platform.V1alpha1PublicInterface)
	return ret0
}

// HyperfleetV1alpha1 indicates an expected call of HyperfleetV1alpha1.
func (mr *MockInterfaceMockRecorder) HyperfleetV1alpha1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HyperfleetV1alpha1", reflect.TypeOf((*MockInterface)(nil).HyperfleetV1alpha1))
}
