// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/openshift-online/rosa-hyperfleet-api/clientset/wrappers/wire_wrappers_generated.go
//
// Generated by this command:
//
//	mockgen-v0.4.0 -source=vendor/github.com/openshift-online/rosa-hyperfleet-api/clientset/wrappers/wire_wrappers_generated.go -package=mocks -destination=pkg/hyperfleet/mocks/wrappers_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	wrappers "github.com/openshift-online/rosa-hyperfleet-api/clientset/wrappers"
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/hyperfleet-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	rest "k8s.io/client-go/rest"
)

// MockClusterInterface is a mock of ClusterInterface interface.
type MockClusterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClusterInterfaceMockRecorder
}

// MockClusterInterfaceMockRecorder is the mock recorder for MockClusterInterface.
type MockClusterInterfaceMockRecorder struct {
	mock *MockClusterInterface
}

// NewMockClusterInterface creates a new mock instance.
func NewMockClusterInterface(ctrl *gomock.Controller) *MockClusterInterface {
	mock := &MockClusterInterface{ctrl: ctrl}
	mock.recorder = &MockClusterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterInterface) EXPECT() *MockClusterInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClusterInterface) Create(ctx context.Context, obj *v1alpha1.Cluster, opts wrappers.CreateOptions) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj, opts)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClusterInterfaceMockRecorder) Create(ctx, obj, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClusterInterface)(nil).Create), ctx, obj, opts)
}

// Delete mocks base method.
func (m *MockClusterInterface) Delete(ctx context.Context, name string, opts wrappers.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterInterfaceMockRecorder) Delete(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterInterface)(nil).Delete), ctx, name, opts)
}

// Get mocks base method.
func (m *MockClusterInterface) Get(ctx context.Context, name string, opts wrappers.GetOptions) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name, opts)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterInterfaceMockRecorder) Get(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterInterface)(nil).Get), ctx, name, opts)
}

// List mocks base method.
func (m *MockClusterInterface) List(ctx context.Context, opts wrappers.ListOptions) (*v1alpha1.ClusterList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(*v1alpha1.ClusterList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterInterfaceMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterInterface)(nil).List), ctx, opts)
}

// Patch mocks base method.
func (m *MockClusterInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts wrappers.PatchOptions) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, name, pt, data, opts)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockClusterInterfaceMockRecorder) Patch(ctx, name, pt, data, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockClusterInterface)(nil).Patch), ctx, name, pt, data, opts)
}

// Update mocks base method.
func (m *MockClusterInterface) Update(ctx context.Context, obj *v1alpha1.Cluster, opts wrappers.UpdateOptions) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj, opts)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterInterfaceMockRecorder) Update(ctx, obj, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterInterface)(nil).Update), ctx, obj, opts)
}

// WaitUntil mocks base method.
func (m *MockClusterInterface) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.Cluster) bool, interval, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntil", ctx, id, condition, interval, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitUntil indicates an expected call of WaitUntil.
func (mr *MockClusterInterfaceMockRecorder) WaitUntil(ctx, id, condition, interval, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntil", reflect.TypeOf((*MockClusterInterface)(nil).WaitUntil), ctx, id, condition, interval, timeout)
}

// MockNodePoolInterface is a mock of NodePoolInterface interface.
type MockNodePoolInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNodePoolInterfaceMockRecorder
}

// MockNodePoolInterfaceMockRecorder is the mock recorder for MockNodePoolInterface.
type MockNodePoolInterfaceMockRecorder struct {
	mock *MockNodePoolInterface
}

// NewMockNodePoolInterface creates a new mock instance.
func NewMockNodePoolInterface(ctrl *gomock.Controller) *MockNodePoolInterface {
	mock := &MockNodePoolInterface{ctrl: ctrl}
	mock.recorder = &MockNodePoolInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodePoolInterface) EXPECT() *MockNodePoolInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNodePoolInterface) Create(ctx context.Context, obj *v1alpha1.NodePool, opts wrappers.CreateOptions) (*v1alpha1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj, opts)
	ret0, _ := ret[0].(*v1alpha1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNodePoolInterfaceMockRecorder) Create(ctx, obj, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNodePoolInterface)(nil).Create), ctx, obj, opts)
}

// Delete mocks base method.
func (m *MockNodePoolInterface) Delete(ctx context.Context, name string, opts wrappers.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNodePoolInterfaceMockRecorder) Delete(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNodePoolInterface)(nil).Delete), ctx, name, opts)
}

// Get mocks base method.
func (m *MockNodePoolInterface) Get(ctx context.Context, name string, opts wrappers.GetOptions) (*v1alpha1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name, opts)
	ret0, _ := ret[0].(*v1alpha1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNodePoolInterfaceMockRecorder) Get(ctx, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNodePoolInterface)(nil).Get), ctx, name, opts)
}

// List mocks base method.
func (m *MockNodePoolInterface) List(ctx context.Context, opts wrappers.ListOptions) (*v1alpha1.NodePoolList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(*v1alpha1.NodePoolList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNodePoolInterfaceMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNodePoolInterface)(nil).List), ctx, opts)
}

// Patch mocks base method.
func (m *MockNodePoolInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts wrappers.PatchOptions) (*v1alpha1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, name, pt, data, opts)
	ret0, _ := ret[0].(*v1alpha1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockNodePoolInterfaceMockRecorder) Patch(ctx, name, pt, data, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockNodePoolInterface)(nil).Patch), ctx, name, pt, data, opts)
}

// Update mocks base method.
func (m *MockNodePoolInterface) Update(ctx context.Context, obj *v1alpha1.NodePool, opts wrappers.UpdateOptions) (*v1alpha1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, obj, opts)
	ret0, _ := ret[0].(*v1alpha1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNodePoolInterfaceMockRecorder) Update(ctx, obj, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNodePoolInterface)(nil).Update), ctx, obj, opts)
}

// WaitUntil mocks base method.
func (m *MockNodePoolInterface) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.NodePool) bool, interval, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntil", ctx, id, condition, interval, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitUntil indicates an expected call of WaitUntil.
func (mr *MockNodePoolInterfaceMockRecorder) WaitUntil(ctx, id, condition, interval, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntil", reflect.TypeOf((*MockNodePoolInterface)(nil).WaitUntil), ctx, id, condition, interval, timeout)
}

// MockV1alpha1Interface is a mock of V1alpha1Interface interface.
type MockV1alpha1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockV1alpha1InterfaceMockRecorder
}

// MockV1alpha1InterfaceMockRecorder is the mock recorder for MockV1alpha1Interface.
type MockV1alpha1InterfaceMockRecorder struct {
	mock *MockV1alpha1Interface
}

// NewMockV1alpha1Interface creates a new mock instance.
func NewMockV1alpha1Interface(ctrl *gomock.Controller) *MockV1alpha1Interface {
	mock := &MockV1alpha1Interface{ctrl: ctrl}
	mock.recorder = &MockV1alpha1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockV1alpha1Interface) EXPECT() *MockV1alpha1InterfaceMockRecorder {
	return m.recorder
}

// Clusters mocks base method.
func (m *MockV1alpha1Interface) Clusters(namespace string) wrappers.ClusterInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clusters", namespace)
	ret0, _ := ret[0].(wrappers.ClusterInterface)
	return ret0
}

// Clusters indicates an expected call of Clusters.
func (mr *MockV1alpha1InterfaceMockRecorder) Clusters(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clusters", reflect.TypeOf((*MockV1alpha1Interface)(nil).Clusters), namespace)
}

// NodePools mocks base method.
func (m *MockV1alpha1Interface) NodePools(namespace string) wrappers.NodePoolInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodePools", namespace)
	ret0, _ := ret[0].(wrappers.NodePoolInterface)
	return ret0
}

// NodePools indicates an expected call of NodePools.
func (mr *MockV1alpha1InterfaceMockRecorder) NodePools(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodePools", reflect.TypeOf((*MockV1alpha1Interface)(nil).NodePools), namespace)
}

// RESTClient mocks base method.
func (m *MockV1alpha1Interface) RESTClient() rest.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTClient")
	ret0, _ := ret[0].(rest.Interface)
	return ret0
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockV1alpha1InterfaceMockRecorder) RESTClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTClient", reflect.TypeOf((*MockV1alpha1Interface)(nil).RESTClient))
}
