name: build-release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2

    steps:
      - name: debug
        run: echo Hello ROSA version ${{ github.event.inputs.releaseTag }}

      - name: checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Make build
        run: make install

      - name: Check build OK
        run: rosa version

      - name: Login to Github CLI
        run: echo ${{env.GIHTUB_TOKEN}} | gh auth login --with-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release
        run: gh release create v${{ github.event.inputs.releaseTag }} ./rosa
