name: build-release

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2

    steps:
      - name: debug
        run: echo Hello ROSA

      - name: checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'

      - name: Make build
        run: make install

      - name: Check build OK
        run: rosa version

      - name: Login to Github CLI
        run: echo  ${{ secrets.GITHUB_TOKEN }}| gh auth login --with-token

      - name: ls
        run: ls -liah

      - name: whereis rosa
        run: which rosa
      
      - name: Create tar bundle
        run: tar -C $(dirname $(which rosa)) -czvf rosa.tar.gz rosa

      - name: Generate release
        run: gh release create rosa-$(date +%Y%m%d_%H%M%S) rosa.tar.gz

